routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/list', 'CameraController@list')->name('list');
Route::get('/show/{camera}', 'CameraController@show')->name('show');
Route::resource('rent', 'RentController', ['only' => ['index','store']]);

Route::group(array('middleware' => 'role:' . \App\Models\User::ROLE_ADMIN), function () {
    Route::resource('camera', 'CameraController', ['except' => ['show']]);
});

app/Models/Camera.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Camera extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'image', 'mark', 'model', 'type', 'resolution', 'flash_lamp', 'memory_cards', 'communication', 'ISO', 'price', 'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at',
    ];
}

app/Models/Rent.php
<?php

namespace App\Models;

use App\Models\Camera;
use Illuminate\Database\Eloquent\Model;

class Rent extends Model
{
    protected $table = 'camera_rent';

    protected $fillable = [
        'count_day', 'price_all',
    ];

    public function cameras() {
        return $this->belongsTo(Camera::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    const ROLE_ADMIN = 2;
    const ROLE_USER = 1;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Checks the admin
     *
     * @return bool
     */
    public function isAdmin()
    {
        return $this->role == User::ROLE_ADMIN;
    }

    /**
     * Check the role
     *
     * @param $role
     * @return bool
     */
    public function hasRole($role)
    {
        return $this->role == $role;
    }
}

app/Http/Controllers/CameraController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CameraRequest;
use App\Models\Camera;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;

class CameraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cameras = Camera::all();
        return view('cameras.index', compact('cameras'));
    }

    public function list()
    {
        $cameras = Camera::all()->where('status',1);
        return view('cameras.list', compact('cameras'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cameras/edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CameraRequest $request, $id = null)
    {
        $camera = $id ? Camera::find($id) : new Camera();
        $camera->fill($request->input());
        if ($request->file('image')) {
            $camera->save();
            Storage::disk('public')->delete($camera->image);
            $camera->image = Storage::disk('public')->putFileAs('CamerasPhotos', $request->file('image'), $camera->id . '_image' . '.' . $request->file('image')->getClientOriginalExtension());
        }
        $camera->save();
        return Redirect::to('camera');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $camera = Camera::find($id);
        Session::put('id',$id);
        return view('cameras.show', compact('camera'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id=null)
    {
        $camera = Camera::find($id);
        if (empty($camera)) {
            return redirect()->action('CameraController@index');
        }
        return view('cameras/edit', compact('camera'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CameraRequest $request, $id)
    {
        return $this->store($request, $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Camera::destroy($id);
        return back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/RentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RentRequest;
use App\Models\Camera;
use App\Models\Rent;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class RentController extends Controller
{
    public function index()
    {
        $rents = DB::table('camera_rent')->leftJoin('cameras','camera_rent.camera_id','=','cameras.id')->where('user_id',Auth::user()->id)->get();
        return view('rents.index', compact('rents'));
    }

    public function store(RentRequest $request)
    {
        $rent = new Rent();
        $id = Session::get('id');
        $camera = Camera::find($id);
        $rent->fill($request->input());
        $rent->user_id = Auth::user()->id;
        $rent->camera_id = (int)$id;
        $rent->price_all = $camera->price * $rent->count_day;
        $camera->update(['status' => 0]);
        $rent->save();
        Session::flash('camera_rents','Zarezerwowałeś aparat, szczegóły zobaczysz na swoim profilu.');
        return Redirect::to('list');
    }

}

resources/views/cameras/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <center>
                    <h2>@if(empty($camera->id)) Dodaj nowy aparat @else Edytuj aparat @endif </h2>
                </center>
            </div>
            <div class="panel-body">
                @if(\Illuminate\Support\Facades\Auth::user())
                    @if(empty($camera->id))
                        {{ Form::open(['route'=>'camera.store','class'=>'form-horizontal','files'=>'true']) }}
                    @else
                        {{ Form::open(['route' => ['camera.update',$camera->id],'class'=>'form-horizontal', 'files'=>'true', 'method'=>'PUT']) }}
                    @endif
                    {{ csrf_field() }}

                    {{ Form::label('image', 'Obraz', ['class'=>'control-label col-md-3']) }}
                    <div class="col-md-9">
                        {{ Form::file('image', ['style'=>'padding-bottom: 5px']) }}
                    </div>
                    @if ($errors->has('image'))
                        <span class="help-block">
                            <strong>{{ $errors->first('image') }}</strong>
                        </span>
                    @endif

                    {{Form::label('mark', 'Marka aparatu', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::text('mark', (empty($camera->id) ? null : $camera->mark), ['class'=>'form-control','id'=>'mark'])}}
                        @if ($errors->has('mark'))
                            <span class="help-block">
                            <strong>{{ $errors->first('mark') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('model', 'Model', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::text('model', (empty($camera->id) ? null : $camera->model), ['class'=>'form-control','id'=>'model'])}}
                        @if ($errors->has('model'))
                            <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('type', 'Typ', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::text('type', (empty($camera->id) ? null : $camera->type), ['class'=>'form-control','id'=>'type'])}}
                        @if ($errors->has('type'))
                            <span class="help-block">
                            <strong>{{ $errors->first('type') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('resolution', 'Rozdzielczość', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::text('resolution', (empty($camera->id) ? null : $camera->resolution), ['class'=>'form-control','id'=>'resolution'])}}
                        @if ($errors->has('resolution'))
                            <span class="help-block">
                            <strong>{{ $errors->first('resolution') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('flash_lamp', 'Lampa_błyskowa', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::text('flash_lamp', (empty($camera->id) ? null : $camera->flash_lamp), ['class'=>'form-control','id'=>'flash_lamp'])}}
                        @if ($errors->has('flash_lamp'))
                            <span class="help-block">
                            <strong>{{ $errors->first('flash_lamp') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('memory_cards', 'Pamięć', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::number('memory_cards', (empty($camera->id) ? null : $camera->memory_cards), ['class'=>'form-control','id'=>'memory_cards'])}}
                        @if ($errors->has('memory_cards'))
                            <span class="help-block">
                            <strong>{{ $errors->first('memory_cards') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('communication', 'Komunikacja', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::text('communication', (empty($camera->id) ? null : $camera->communication), ['class'=>'form-control','id'=>'communication'])}}
                        @if ($errors->has('communication'))
                            <span class="help-block">
                            <strong>{{ $errors->first('communication') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('ISO', 'Czułość ISO', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::text('ISO', (empty($camera->id) ? null : $camera->ISO), ['class'=>'form-control','id'=>'ISO'])}}
                        @if ($errors->has('ISO'))
                            <span class="help-block">
                            <strong>{{ $errors->first('ISO') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('price', 'Cena wypożyczenia', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 5px">
                        {{Form::text('price', (empty($camera->id) ? null : $camera->price), ['class'=>'form-control','id'=>'price'])}}
                        @if ($errors->has('price'))
                            <span class="help-block">
                            <strong>{{ $errors->first('price') }}</strong>
                        </span>
                        @endif
                    </div>

                    {{Form::label('status', 'Dostępność', ['class'=>'control-label col-md-3'])}}
                    <div class="col-md-9" style="padding-bottom: 10px">
                        {{Form::select('status', ['1'=> 'dostępny', '0'=>'niedostępny'],empty($camera->id) ? 1 : $camera->status,['id'=>'status','class'=>'form-control'])}}
                        @if ($errors->has('status'))
                            <span class="help-block">
                            <strong>{{ $errors->first('status') }}</strong>
                        </span>
                        @endif
                    </div>

                    <br/>

                    <div class="form-group">
                    {{Form::submit('Zapisz',['class'=>'btn btn-primary'])}}
                    {{Html::link('camera','Cofnij',['class'=>'btn btn-default'])}}
                    </div>

                    {{ Form::close() }}

                @else
                    <p>Nie masz dostępu do tej strony!</p>
                @endif
            </div>
        </div>
    </div>



    <script src="{{ asset('js/edit_recipe.js') }}"></script>
@endsection

resources/views/cameras/index.blade.php
@extends('layouts.app')

@section('content')


    <div class="container">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2>Aparaty fotograficzne</h2>
            </div>
            <div class="panel-body">
                @if (Auth::user()->isAdmin())

                    <div class="row">
                        <div class="col-sm-12 text-right">
                            <a href="{{ route('camera.create') }}" class="btn btn-primary">Dodaj aparat</a>
                        </div>
                    </div>

                    <div class="container-fluid">
                        <div class="row">
                            <h5 class="col-md-2">Marka</h5>
                            <h5 class="col-md-2">Model</h5>
                            <h5 class="col-md-1">Typ</h5>
                            <h5 class="col-md-2">Czułość ISO</h5>
                            <h5 class="col-md-1">Cena wypożyczenia</h5>
                            <h5 class="col-md-1">Dostępność</h5>
                        </div>

                        @foreach ($cameras as $camera)
                            <div class="row">
                                <p class="col-md-2" style="padding-bottom: 5px">{{ $camera->mark }}</p>
                                <p class="col-md-2" style="padding-bottom: 5px">{{ $camera->model }}</p>
                                <p class="col-md-1" style="padding-bottom: 5px">{{ $camera->type }}</p>
                                <p class="col-md-2" style="padding-bottom: 5px">{{ $camera->ISO }}</p>
                                <p class="col-md-1" style="padding-bottom: 5px">{{ $camera->price }}</p>
                                <p class="col-md-1"
                                   style="padding-bottom: 5px">{{ $camera->status==1 ? 'dostępny' : 'niedostępny' }}</p>

                                <div class="col-md-2 text-right">
                                    <div class="col-md-6">
                                        <a href="{{ route('camera.edit', ['id' => $camera->id]) }}"
                                           class="btn btn-primary">{{ 'Edytuj' }}</a>
                                    </div>
                                    <div class="col-md-6">
                                        {{ Form::open(['route' => ['camera.destroy',$camera->id],'method'=>'DELETE']) }}
                                        {{ Form::submit('Usuń', ['class' => 'btn btn-danger']) }}
                                        {{Form::close()}}
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>

                @else
                    <p>Nie masz dostępu do tej strony!</p>
                @endif
            </div>
        </div>
    </div>
    </div>


@endsection

resources/views/cameras/list.blade.php
@extends('layouts.app')

@section('content')


    <div class="container">
        @if (Session::has('camera_rents'))
            <div class="alert alert-success">{{ Session::get('camera_rents') }}</div>
        @endif
        <div class="panel panel-info">
            <div class="panel-heading">
                <h2>Aparaty fotograficzne</h2>
            </div>
            <div class="panel-body">
                @if (Auth::user())
                    <div class="container-fluid">

                        @foreach ($cameras as $camera)
                            <div class="col-md-3">
                                <div class="card">
                                    <a href="{{route('show',$camera->id)}}"><img class="card-img-top" src="./{{Storage::url($camera->image)}}" alt="Image" height="250" width="200"></a>
                                    <div class="card-body">
                                        <h4 class="card-title text-center">{{$camera->mark}} {{$camera->model}}</h4>
                                        <p class="card-text text-right">Cena: {{$camera->price}} zł</p>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>

                @else
                    <p>Nie masz dostępu do tej strony!</p>
                @endif
            </div>
        </div>
    </div>
    </div>


@endsection

resources/views/cameras/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="panel panel-info">
            <div class="panel-body">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                @if(Auth::user())
                    <div class="panel panel-default">
                        <div class="row" style="padding-left: 30px; padding-right: 30px">
                            <div class="col-md-7 text-center">
                                <img src="/wypozyczalnia/storage/app/public/{{$camera->image}}" alt="Image" height="400"
                                     width="400">
                            </div>
                            <div class="col-md-5" style="padding-top: 40px">
                                <h2> {{ $camera->mark }} {{ $camera->model }} </h2>
                                <h4> Cena wypożyczenia za dobę: {{ $camera->price }}</h4>
                                <div class="row">
                                    <div class="col-md-12">
                                        {{ Form::open(['route'=>'rent.store','class'=>'form-horizontal']) }}
                                        {{ csrf_field() }}

                                        {{Form::label('count_day', 'Ilość dni', ['class'=>'control-label col-md-3'])}}
                                        <div class="col-md-9" style="padding-bottom: 5px">
                                            {{Form::number('count_day', null, ['class'=>'form-control','id'=>'count_day'])}}
                                            @if ($errors->has('count_day'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('count_day') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        {{--{{Form::label('price_all', 'Cena (całkowita)', ['class'=>'control-label col-md-3'])}}--}}
                                        {{--<div class="col-md-9" style="padding-bottom: 5px">--}}
                                            {{--{{Form::text('price_all', (empty($camera->id) ? null : $camera->price), ['class'=>'form-control','id'=>'price_all'])}}--}}
                                            {{--@if ($errors->has('price_all'))--}}
                                                {{--<span class="help-block">--}}
                                                    {{--<strong>{{ $errors->first('price_all') }}</strong>--}}
                                                {{--</span>--}}
                                            {{--@endif--}}
                                        {{--</div>--}}

                                        <br/>
                                        <br/>
                                        {{Form::submit('Wypożycz',['class'=>'btn btn-dark btn-block'])}}
                                    {{ Form::close() }}

                                </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h2> Parametry aparatu: </h2>
                        </div>
                        <div class="panel-body">
                            <h4><label>Marka: </label> {{ $camera->mark }}</h4>
                            <h4><label>Model aparatu: </label> {{ $camera->model }}</h4>
                            <h4><label>Typ aparatu: </label> {{ $camera->type }}</h4>
                            <h4><label>Rozdzielczość (Mpix): </label> {{ $camera->resolution }}</h4>
                            <h4><label>Lampa błyskowa: </label> {{ $camera->flash_lamp }}</h4>
                            <h4><label>Pamięć: </label> {{ $camera->memory_cards }}</h4>
                            <h4><label>Komunikacja: </label> {{ $camera->communication }}</h4>
                            <h4><label>Czułość ISO: </label> {{ $camera->ISO }}</h4>
                        </div>

                    </div>
                @else
                    <p>Nie masz dostępu do tej strony!</p>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="panel panel-success">
                    <div class="panel-heading"><h2>Wypożyczalnia aparatów fotograficznych</h2></div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @guest
                            <h4>Witamy w naszej wypożyczalni, aby kontynuować musisz się zalogować.</h4>
                            <h4>Jeśli nie posiadasz konta zachęcamy do rejestracji.</h4>
                        @else
                            @if (Auth::user()->isAdmin())
                                <h4> Jesteś adminem możesz zarządzać wypożyczalnią</h4>
                            @else
                                <h4>Witamy w naszej wypożyczalni.</h4>
                                <h4>Życzymy miłego pobytu na naszej stronie.</h4>
                            @endif
                        @endguest
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ 'Wypożyczalnia' }}</title>

    <!-- Scripts -->
    {{--<script src="{{ asset('js/app.js') }}" defer></script>--}}
    <script src="js/bootstrap.min.js"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
    {{--<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet"/>--}}
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-default navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ 'Wypożyczalnia' }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav navbar-left">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">Logowanie</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">Rejestracja</a></li>
                        @else
                            @if (Auth::user()->isAdmin())
                                <li class="navbar-brand"><a href="{{ route('camera.index') }}">{{ "Aparaty fotograficzne" }}</a></li>
                            @else
                                <li class="navbar-brand"><a href="{{ route('list') }}">{{ "Aparaty fotograficzne" }}</a></li>
                            @endif
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('rent.index') }}">
                                        Profil
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Wyloguj') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>